#!/usr/bin/env python3

import argparse, time, math, sys

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Pango Rise Wrapper')
    parser.add_argument('-start', '--start', type=float, default=0.5)
    parser.add_argument('-w',     '--wait',  type=float, default=1)
    parser.add_argument('-end',   '--end',   type=float, default=0.5)
    
    args = parser.parse_args()
    
    now = time.time()

    for line in sys.stdin:
        delta = time.time() - now
        if delta < args.start:
            pct = delta / args.start
        elif delta < args.start + args.wait:
            pct = 1
        fade = "<span alpha='{}%'>{}</span>".format(round(max(pct, 0.01) * 100), line.strip())
        print(fade, flush=True)
