#!/usr/bin/env python3

import sys, time
import numpy as np


if __name__ == "__main__":

    f = 50
    now = time.time()
    delta = 0

    for line in sys.stdin:
        delta = (time.time() - now)
        line = line.strip()
        wave = ""
        for i in range(len(line)):
            x = ((i + delta + 1) / len(line))
            y = int(np.sin(np.pi * f * x) * 10000)
            wave += "<span rise='{}'>{}</span>".format(y, line[i])
        print(wave, flush=True)
